name: cron

on:
  schedule:
    # 매일 10시 (한국시간 24시)
    - cron: '0 10 * * 0-6'

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install requests
      - run: python3 ./scripts/daily_managing.py
    